version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: paalam_db
    restart: always
    env_file:
      - ./.env
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
